// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubxbiicyzwlhyfgenyce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVieGJpaWN5endsaHlmZ2VueWNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MTcyMzAsImV4cCI6MjA1Mzk5MzIzMH0.pe3_qRmARvxxPI42Jtl092P4ysw-P96k9SKxsmSgGzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);